### ISSUE TITLE
Feature Request: add possibility to read envs from parameter store

### ISSUE THREAD

**Issue by tripodsan** [coralogix/aws-lambda-extension#2]
having to deploy the envs (api key, app name, subsystem name) for every function is a bit tedious and also poses a problem if we would want to rotate the key.

it would be cool, if you could specify a parameter store path and the extension would read the envs from there.

for example, instead of specifying: `CORALOGIX_PRIVATE_KEY`, we could specify `CORALOGIX_PRIVATE_KEY_PARAM` with something like `/myproject/dev/coralogix_key` and the extension would read the key from there.

see: https://docs.aws.amazon.com/systems-manager/latest/APIReference/API_GetParameter.html

**Comment by EldarAliiev** [comment]
The problem that extension is isolated and doesn't have IAM permissions.
So, to get values from paramstore you will be need to pass AWS credentials as environment variables.
Does it make sense?

**Comment by tripodsan** [comment]
ah, ok. I see. that would not be very useful then.
