### ISSUE TITLE
Feature Request: use function name as sub-system nane

### ISSUE THREAD

**Issue by tripodsan** [coralogix/aws-lambda-extension#3]
it would be cool, if the extension would auto-configure the `CORALOGIX_SUB_SYSTEM` form function name.
the current behaviour uses `logs` as default sub system, which is a bit poor.

**Comment by EldarAliiev** [comment]
It was an initial idea to use lambda name as default subsystem name. But lambda extension API doesn't provide mechanism to retreive lambda function name. So, it's impossible to implement this.
